### ISSUE TITLE
Do not report `@pytest.mark.skipIf` exceptions

### ISSUE THREAD

**Issue by cdecker** [getsentry/pytest-sentry#6]
We frequently use `@pytest.mark.skipIf` in our test-suite to skip tests that are not runnable in the current environment.

Sadly `pytest-sentry` does not support `@pytest.mark.skipIf`, since it uses exceptions internally to signal whether a test was skipped or not, we get loads of exceptions reported to sentry that are little more than the skipped tests. So much so that ~90% of our sentry quota would be used by skipped tests, and exhausting the quota before we get really helpful exceptions flagged.

It'd be nice to have a way to opt out of reporting these to sentry at all. I know there's server-side filtering, but that's a premium feature that's not well-suited to an open-source project.

**Comment by untitaker** [comment]
We can hardcode ignoring those exceptions in the pytest plugin. Do you want to author a patch for it? 

However to clear two things up: sentry sdk allows you to filter exceptions using before-send. Also this should not be really a problem unless your skipping is a flaky exception that does not happen on every rerun, or if you are using PYTEST_SENTRY_ALWAYS_REPORT

**Comment by cdecker** [comment]
I tried adding a `before_send` hook function as you proposed, however I seem to be failing to identify the correct client, since the function never gets called. If you have pointers on how to correctly register such a filter I can try to create a PR :+1: Ideally I'd wrap the filter into a fixture so future users can add their own filters.

I don't quite understand your correction: I'm not using the always report option, and skipping is used based on environment variables that describe the environment (running in dev-mode, running with experimental features, etc). The tests themselves are not flaky, it's just that they may be slow or not work at all in the current configuration. Nevertheless I get a sentry event reported on each skipped test:

![Selection_047](https://user-images.githubusercontent.com/120117/97298190-5e659580-1853-11eb-83dd-c62a9947528c.png)

**Comment by untitaker** [comment]
We should not report tests that only fail once, only if they fail inconsistently when retried as part of a test session. That's why I am so confused as to why you're encountering this error in the first place. Can you link me one of those events?

I just added tests to master that test skipif and can't repro this

**Comment by cdecker** [comment]
That's interesting, I think the only difference we have is that we run with `--reruns=3` instead of annotating each test individually. Do you think that might be causing the divergent behavior?

**Comment by asottile-sentry** [comment]
here's an internal example -- https://sentry.io/organizations/sentry/issues/3548525526/?project=2423079

perhaps because it's a `unittest` testcase?

**Comment by untitaker** [comment]
it's possible, there's no tests in this library for unittest compat. but i think this is the first time i heard of marker problems like that on unittest classes...

**Comment by asottile-sentry** [comment]
I think the problem is compounded that it's not a marker but an inline `pytest.skip` -- I wonder if using `unittest.skip` avoids it :thinking:

**Comment by untitaker** [comment]
if that is the issue we should just filter out those pytest exceptions here: https://github.com/untitaker/pytest-sentry/blob/c58535e45a8f7f2222f9508659e68aca6ebd8713/pytest_sentry.py#L202

currently we rely on pytest to filter those out for us

**Comment by asottile-sentry** [comment]
@untitaker does this seem useful?
```diff
diff --git a/pytest_sentry.py b/pytest_sentry.py
index f8bfa5d..c9f9515 100644
--- a/pytest_sentry.py
+++ b/pytest_sentry.py
@@ -187,9 +187,10 @@ def pytest_fixture_setup(fixturedef, request):
 def pytest_runtest_makereport(item, call):
     sentry_sdk.set_tag("pytest.result", "pending")
     report = yield
-    sentry_sdk.set_tag("pytest.result", report.get_result().outcome)
+    outcome = report.get_result().outcome
+    sentry_sdk.set_tag("pytest.result", outcome)
 
-    if call.when == "call":
+    if call.when == "call" and outcome != "skipped":
         cur_exc_chain = getattr(item, "pytest_sentry_exc_chain", [])
 
         if call.excinfo is not None:
```

**Comment by untitaker** [comment]
@asottile-sentry this makes sense to me 👍
